language: ruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
    - rvm: rbx-18mode

rvm:
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - 1.8.7
  - ree
  - rbx-18mode
  - jruby-18mode
  - ruby-head
  - jruby-head

env: JRUBY_OPTS=-Xcext.enabled=true
